### NumPy —  Cheatsheet

#### Create
`np.array()`, `np.zeros()`, `np.ones()`, `np.empty()`  
`np.arange()`, `np.linspace()`  
`np.eye()`  
Random: `rand()`, `randn()`, `randint()`

#### Inspect
`a.shape`, `a.ndim`, `a.size`, `a.dtype`

#### Index & Slice
`a[i]`, `a[i:j]`, `a[:, k]`, `a[::2]`  
Boolean: `a[a>0]`  
Fancy: `a[[1,3,5]]`

#### Reshape & Transform
`a.reshape()`, `a.ravel()`, `a.T`  
`np.expand_dims()`, `np.squeeze()`

### Math
Elementwise: `a+b`, `a*b`, `a/b`, `a**2`  
Reduction: `a.sum()`, `a.mean()`, `a.min()`, `a.max()`  
Axis: `a.sum(axis=0)`  
Matrix: `a@b`, `np.dot(a,b)`

#### Combine
`np.concatenate([a,b], axis=0)`  
`np.vstack([a,b])`, `np.hstack([a,b])`

#### Utilities
`np.unique()`, `np.sort()`, `np.argsort()`  
`np.clip()`, `np.isnan()`, `np.nan_to_num()`  

#### Linear Algebra
`np.linalg.solve()`, `inv()`, `det()`, `eig()`, `svd()`

#### Random
`np.random.uniform()`, `normal()`, `choice()`, `shuffle()`

#### Core Rules
**Broadcasting:** dims match or are 1  
**Vectorise:** avoid Python loops  
**Shape first:** fix errors with `reshape` or broadcasting


In [1]:
import numpy as np

#https://www.youtube.com/watch?v=VXU4LSAQDSc

In [2]:
#Create an array of 3, populated with 0
a = np.zeros(3)
a.shape

(3,)

In [3]:
my_list = [1, 2, 3, 4]
second_list = my_list * 2 # Two list side by side
second_list

[1, 2, 3, 4, 1, 2, 3, 4]

In [4]:
array = np.array([1, 2, 3, 4])
second_array = array * 2 # This is smarter. Instead numpy arrays actually multiplies each value by two

print(type(array))
second_array

<class 'numpy.ndarray'>


array([2, 4, 6, 8])

In [5]:
array = np.array([['A', 'B', 'C'],
                  ['D', 'E', 'F'],
                  ['G', 'H', 'I']])
#print(array.ndim) #This can show how many dimensions the array has

word = array[1,2] + array[0,0] + array[0,1]
print(word)

FAB


In [6]:
# Slicing

array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])
# array[start:end:step, col]

rows = array[0:4:2]
columns = array[:, 1:4]
print(columns)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [7]:
# Scalar arithmetic

array = np.array([25,36,49.5])
add = array + 1
sub = array - 2
multiply = array * 3
root = np.sqrt(array)
round = np.round(array)

radii = np.array([1,2,3])
area = (np.pi * radii ** 2) #Area = pi r sqr

#Element wise arithmetic
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
div = array1 / array2
sqr = array1 ** array2

#Comparison operators
score = np.array([91,55,100,73,82,64])
ispass = score >= 100
ispass
score[score < 60] = 0
credit = score.copy()
credit[score < 60] = 0
credit

array([ 91,   0, 100,  73,  82,  64])

In [ ]:
# Broadcasting
array1 = np.array([[1,2,3,4]]) #2D array
array2 = np.array([[1],[2],[3],[4]]) #2D array
array3 = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12],
                   [13,14,15,16]]) #2D array


print(array1.shape)
print(array2.shape)
print(array3.shape)

#They can be broadcast if columns/row numbers match or = 1. 
print(array1 * array2)

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (896162939.py, line 2)

In [ ]:
# Aggregate functions 40mins

array = np.array([[1,2,3,4],
                   [5,6,7,8],
                   [9,10,11,12],
                   [13,14,15,16]])

sum = np.sum(array)
min = np.min(array)
max = np.max(array)
mean = np.mean(array)
std = np.std(array)
var = np.var(array)
var = np.var(array)

sumcolumn = np.sum(array, axis=0) # Sum every column
sumrow = np.sum(array, axis=0) # Sum every row

print(sumcolumn)

[28 32 36 40]


In [13]:
# Filtering - Selecting elements from array that match condition

ages = np.array([[21,17,18,19,20,18,65],
                 [39,22,15,88,18,19,20]])

teens = ages[ages < 19]
adults = ages[(ages >= 18) & (ages < 65)]
adults1 = np.where(ages >= 18, ages, 0) #Replaces values where condition is not met by 0. Maintains shape

print(adults1)




[[21  0 18 19 20 18 65]
 [39 22  0 88 18 19 20]]


In [ ]:
# Random numbers
rng = np.random.default_rng()

randomints = rng.integers(low=1, high=7, size=(3,2))

randomfloats = rng.uniform(low=0, high=1, size=(3,2))


fruits = np.array(["apple","orange","banana","coconut","grapes"])
rng.shuffle(fruits) #This is to shuffle (in object)
print(fruits)

fruit = rng.choice(fruits, size= (3, 3)) #choose one
print(fruit)


['banana' 'grapes' 'orange' 'coconut' 'apple']
[['coconut' 'grapes' 'grapes']
 ['orange' 'coconut' 'coconut']
 ['banana' 'grapes' 'apple']]
